import __PuzzleCheckViewClass from "./component_plain_js.pzl.script.js";
export default __PuzzleCheckViewClass;

// Generated by puzzle check. This function is never executed.
void function (this: InstanceType<typeof __PuzzleCheckViewClass> & Record<string, any>): void {
  const __d = this;
  if (__d.active) {
  } else {
    void __d.tone;
  }
  void __d.title;
  void (__d.draft);
  const __puzzle_check_event_0: ((event: any) => any) | null = (event) => this.events.update(event);
  void __puzzle_check_event_0;
  const __puzzle_check_event_1: ((event: any) => any) | null = this.events.reset;
  void __puzzle_check_event_1;

  // <puzzle-skeleton>
  void __d.loadingLabel;
};
