
import { PuzzleView } from '@magic-spells/puzzle';

export default class MarkerArgs extends PuzzleView {
  members: Array<{ id: number; name: string }> = [];
}

// Generated by puzzle check. This function is never executed.
void function (this: InstanceType<typeof MarkerArgs> & Record<string, any>): void {
  const __d = this;
  void (__d.members.length);
  __puzzle_check_each(__d.members, (member, index) => {
    void (member.id);
    void (member);
    void (index);
    void (member.name);
  });
};
