
import { PuzzleView } from '@magic-spells/puzzle';

export default class ViewScope extends PuzzleView {
  classes = 'ready';
  user: { name: string } | null = null;
  loading = false;
  items: Array<{ done: boolean; label: string }> = [];
  kind = 'alpha';

  events = {
    select: (item: { done: boolean; label: string }, index: number) => ({ item, index }),
  };
}

// Generated by puzzle check. This function is never executed.
void function (this: InstanceType<typeof ViewScope> & Record<string, any>): void {
  const __d = this;
  void (__d.classes);
  void __puzzle_check_formatter("upper", __d.name);
  if (__d.user) {
    void __puzzle_check_formatter("fallback", __d.user.name, 'friend');
  } else {
    if (__d.loading) {
      void __d.status;
    } else {
    }
  }
  __puzzle_check_each(__d.items, (item, index) => {
    void (item.done);
    const __puzzle_check_event_0: ((event: any) => any) | null = (event) => this.events.select(item, index);
    void __puzzle_check_event_0;
    void index;
    void item.label;
  });
  switch (__d.kind) {
    case 'alpha':
    case 'beta':
      void __d.kind;
      break;
    default:
      void __d.fallbackLabel;
  }
};
