
import { PuzzleView } from '@magic-spells/puzzle';
import Roster from '../components/Roster.pzl';

export default class ViewSnippets extends PuzzleView {
  caption = 'the roster';
  team: Array<{ id: number; name: string }> = [];
}

// Generated by puzzle check. This function is never executed.
void function (this: InstanceType<typeof ViewSnippets> & Record<string, any>): void {
  const __d = this;
  void (__d.team);
  __puzzle_check_snippet((total) => {
    void (total);
    void (__d.caption);
  });
  __puzzle_check_snippet((member, index) => {
    void (index + 1);
    void (__d.caption);
    void (member.name);
  });
};
