
import { PuzzleView } from '@magic-spells/puzzle';
import Frame from '../components/Frame';

export default class ViewComponentFamily extends PuzzleView {
  title = 'Frame';
  body = '';

  events = {
    dismiss: (event: Event) => event.type,
  };
}

// Generated by puzzle check. This function is never executed.
void function (this: InstanceType<typeof ViewComponentFamily> & Record<string, any>): void {
  const __d = this;
  void (__d.title);
  const __puzzle_check_event_0: ((event: any) => any) | null = (event) => this.events.dismiss(event);
  void __puzzle_check_event_0;
  void (__d.body);
};
