/**
 * Shared helpers for the stress scenarios.
 *
 * Everything here is deliberately dependency-free and deterministic: a harness
 * whose own scaffolding varies run to run cannot produce a comparable number.
 */

/** Fixed fixture seed — every run generates byte-identical record values. */
export const STRESS_SEED = 0x51a7e55;

export const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

/** One animation frame (falls back to a timer in a hidden tab / non-DOM host). */
export function nextFrame() {
	return new Promise((resolve) => {
		const hidden = typeof document !== 'undefined' && document.hidden;
		if (typeof requestAnimationFrame === 'function' && !hidden) requestAnimationFrame(resolve);
		else setTimeout(resolve, 0);
	});
}

/**
 * Resolve AFTER the browser has painted. rAF callbacks run BEFORE paint, so the
 * canonical spelling is rAF → setTimeout(0): the timer lands in the task queue
 * once the frame has been committed. This is the difference between timing
 * "the framework finished mutating the DOM" and "the user can see it".
 */
export function afterPaint() {
	return new Promise((resolve) => {
		const hidden = typeof document !== 'undefined' && document.hidden;
		if (typeof requestAnimationFrame !== 'function' || hidden) {
			setTimeout(resolve, 0);
			return;
		}
		requestAnimationFrame(() => setTimeout(resolve, 0));
	});
}

/** Drain the microtask queue and `count` frames. */
export async function settleFrames(count = 2) {
	await Promise.resolve();
	for (let i = 0; i < count; i += 1) await nextFrame();
	await Promise.resolve();
}

/** Reject if `promise` has not settled within `ms` — keeps a wedged op from hanging run(). */
export function withTimeout(promise, ms, message) {
	let timer = null;
	const guard = new Promise((_, reject) => {
		timer = setTimeout(() => reject(new Error(message || `[stress] timed out after ${ms}ms`)), ms);
	});
	return Promise.race([promise, guard]).finally(() => clearTimeout(timer));
}

/**
 * Destroy every record of `type`.
 *
 * NOTE: `findMany` auto-subscribes the CURRENT tracking scope, so this must only
 * ever be called OUTSIDE `data()` — from `created()`, an event handler, or a
 * scenario op. Every call site here satisfies that.
 */
export function clearType(store, type) {
	const records = store.findMany(type);
	for (const record of records) record.destroy();
	return records.length;
}

/**
 * Shapes for `store.seed(type, shapes)` that pin `seq` to insertion order.
 *
 * `findMany` returns records in Map-insertion order, which cannot be permuted in
 * place — so `swap-rows` needs an explicit ordering field. `seq` is it: the
 * scenario sorts by `seq` in `data()`, and a swap is two `record.update()`
 * calls that go through the normal reactive path. Every other field on the
 * record is still schema-generated by the fixtures module.
 */
export function seqShapes(count, startSeq = 0) {
	const shapes = new Array(count);
	for (let i = 0; i < count; i += 1) shapes[i] = { seq: startSeq + i };
	return shapes;
}

/** Sort comparator for records carrying `seq`. */
export const bySeq = (a, b) => a.seq - b.seq;

/** Clamped integer from an untyped (query-param) value. */
export function intParam(value, fallback, min = 0, max = 1000000) {
	const n = Number(Array.isArray(value) ? value[0] : value);
	if (!Number.isFinite(n)) return fallback;
	return Math.max(min, Math.min(max, Math.trunc(n)));
}

/**
 * The DOM subtree a scenario's `validate()` should inspect. Prefers the view's
 * own root element; falls back to the stage container (which holds exactly one
 * scenario at a time) when the root is still an anchor comment.
 */
export function viewRoot(view) {
	const el = view?.element;
	if (el && typeof el.querySelectorAll === 'function') return el;
	if (typeof document === 'undefined') return null;
	return document.getElementById('scenario-stage');
}

/** Round to 1 decimal for display. */
export const ms1 = (n) => Math.round(n * 10) / 10;

// ---------------------------------------------------------------------------
// Framework structural counters (development builds only).
//
// `client-runtime/devperf.js` installs a frozen `globalThis.__PUZZLE_PERF__`
// with a `snapshot()` of its running totals. It is dev-only by construction:
// production defines `__PUZZLE_DEV__` as false and esbuild removes the module,
// so the global simply does not exist in a production bundle and every helper
// here degrades to `null` rather than throwing.
//
// That split is exactly the right one for this harness. TIMINGS must come from
// the production bundle (see benchmarks/runner.mjs) because that is what users
// run. STRUCTURAL COUNTS — how many views re-rendered, how many of those
// renders mutated nothing, how many component patches took the shallowEqual
// bailout — are properties of the render algorithm, not of the build mode, and
// are only observable where the instrumentation survives. Run the harness with
// `--build-mode development` to collect them, and never quote that run's
// milliseconds.
// ---------------------------------------------------------------------------

/** Counters worth differencing across a single op. */
const PERF_KEYS = [
	'renders',
	'wastedRenders',
	'dataRuns',
	'domMutations',
	'componentPropBailouts',
	'componentPropReruns',
	'storeFlushes',
	'storeNotifications',
];

/** Frozen totals from the dev-only profiler, or null in a production build. */
export function perfSnapshot() {
	const perf = typeof globalThis === 'undefined' ? null : globalThis.__PUZZLE_PERF__;
	return typeof perf?.snapshot === 'function' ? perf.snapshot() : null;
}

/**
 * Difference a snapshot taken before an op against the totals now.
 *
 * Returns null when the profiler is absent (production) so callers can report
 * "not measurable in this build" rather than a fabricated zero — a zero here
 * and a real zero mean opposite things.
 */
export function perfDelta(before) {
	const after = perfSnapshot();
	if (!before || !after) return null;
	const out = {};
	for (const key of PERF_KEYS) out[key] = (after[key] ?? 0) - (before[key] ?? 0);
	return out;
}
